default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['db_host'] || 'postgres' %>
  username: <%= ENV['db_user'] || 'postgres' %>
  password: <%= ENV['db_pass'] || 'postgres' %>
  port: <%= ENV['db_port'] || 5432 %>

development:
  <<: *default
  database: mock_recharges_app_development

test:
  <<: *default
  database: mock_recharges_app_test

production:
  <<: *default
  database: mock_recharges_app_production
